export const GET_MENUS_LIST_REQUEST = '@@menu/GET_MENUS_LIST_REQUEST';
export type GET_MENUS_LIST_REQUEST = typeof GET_MENUS_LIST_REQUEST;

export const GET_MENUS_LIST_SUCCESS = '@@menu/GET_MENUS_LIST_SUCCESS';
export type GET_MENUS_LIST_SUCCESS = typeof GET_MENUS_LIST_SUCCESS;

export const GET_MENUS_LIST_FAILURE = '@@menu/GET_MENUS_LIST_FAILURE';
export type GET_MENUS_LIST_FAILURE = typeof GET_MENUS_LIST_FAILURE;

export const ADD_MENU_REQUEST = '@@menu/ADD_MENU_REQUEST';
export type ADD_MENU_REQUEST = typeof ADD_MENU_REQUEST;

export const ADD_MENU_SUCCESS = '@@menu/ADD_MENU_SUCCESS';
export type ADD_MENU_SUCCESS = typeof ADD_MENU_SUCCESS;

export const ADD_MENU_FAILURE = '@@menu/ADD_MENU_FAILURE';
export type ADD_MENU_FAILURE = typeof ADD_MENU_FAILURE;

export const CHANGE_MENU_REQUEST = '@@menu/CHANGE_MENU_REQUEST';
export type CHANGE_MENU_REQUEST = typeof CHANGE_MENU_REQUEST;

export const CHANGE_MENU_SUCCESS = '@@menu/CHANGE_MENU_SUCCESS';
export type CHANGE_MENU_SUCCESS = typeof CHANGE_MENU_SUCCESS;

export const CHANGE_MENU_FAILURE = '@@menu/CHANGE_MENU_FAILURE';
export type CHANGE_MENU_FAILURE = typeof CHANGE_MENU_FAILURE;

export const DELETE_MENU_REQUEST = '@@menu/DELETE_MENU_REQUEST';
export type DELETE_MENU_REQUEST = typeof DELETE_MENU_REQUEST;

export const DELETE_MENU_SUCCESS = '@@menu/DELETE_MENU_SUCCESS';
export type DELETE_MENU_SUCCESS = typeof DELETE_MENU_SUCCESS;

export const DELETE_MENU_FAILURE = '@@menu/DELETE_MENU_FAILURE';
export type DELETE_MENU_FAILURE = typeof DELETE_MENU_FAILURE;

export const MENU_FORM_NAME = 'menu';
