const APP_STORE_CONSTANTS = {
  TYPE_ADD_LOADING: 'TYPE_ADD_LOADING',
  TYPE_REMOVE_LOADING: 'TYPE_REMOVE_LOADING',
  TYPE_SWITCH_THEME: 'TYPE_SWITCH_THEME',
};

export default APP_STORE_CONSTANTS;
