export const GET_USERS_REQUEST = '@@user/GET_USERS_REQUEST';
export type GET_USERS_REQUEST_TYPE = typeof GET_USERS_REQUEST;

export const GET_USERS_SUCCESS = '@@user/GET_USERS_SUCCESS';
export type GET_USERS_SUCCESS_TYPE = typeof GET_USERS_SUCCESS;

export const GET_USERS_FAILURE = '@@user/GET_USERS_FAILURE';
export type GET_USERS_FAILURE_TYPE = typeof GET_USERS_FAILURE;

export const CHANGE_USER_REQUEST = '@@user/CHANGE_USER_REQUEST';
export type CHANGE_USER_REQUEST_TYPE = typeof CHANGE_USER_REQUEST;

export const CHANGE_USER_SUCCESS = '@@user/CHANGE_USER_SUCCESS';
export type CHANGE_USER_SUCCESS_TYPE = typeof CHANGE_USER_SUCCESS;

export const CHANGE_USER_FAILURE = '@@user/CHANGE_USER_FAILURE';
export type CHANGE_USER_FAILURE_TYPE = typeof CHANGE_USER_FAILURE;

export const CREATE_USER_REQUEST = '@@user/CREATE_USER_REQUEST';
export type CREATE_USER_REQUEST_TYPE = typeof CREATE_USER_REQUEST;

export const CREATE_USER_SUCCESS = '@@user/CREATE_USER_SUCCESS';
export type CREATE_USER_SUCCESS_TYPE = typeof CREATE_USER_SUCCESS;

export const CREATE_USER_FAILURE = '@@user/CREATE_USER_FAILURE';
export type CREATE_USER_FAILURE_TYPE = typeof CREATE_USER_FAILURE;

export const DELETE_USER_REQUEST = '@@user/DELETE_USER_REQUEST';
export type DELETE_USER_REQUEST_TYPE = typeof DELETE_USER_REQUEST;

export const DELETE_USER_SUCCESS = '@@user/DELETE_USER_SUCCESS';
export type DELETE_USER_SUCCESS_TYPE = typeof DELETE_USER_SUCCESS;

export const DELETE_USER_FAILURE = '@@user/DELETE_USER_FAILURE';
export type DELETE_USER_FAILURE_TYPE = typeof DELETE_USER_FAILURE;

export const USER_FORM_NAME = 'user';
