export const GET_SETTINGS_REQUEST = '@@settings/GET_SETTINGS_REQUEST';
export type GET_SETTINGS_REQUEST = typeof GET_SETTINGS_REQUEST;

export const GET_SETTINGS_SUCCESS = '@@settings/GET_SETTINGS_SUCCESS';
export type GET_SETTINGS_SUCCESS = typeof GET_SETTINGS_SUCCESS;

export const GET_SETTINGS_FAILURE = '@@settings/GET_SETTINGS_FAILURE';
export type GET_SETTINGS_FAILURE = typeof GET_SETTINGS_FAILURE;

export const CHANGE_SETTINGS_REQUEST = '@@settings/CHANGE_SETTINGS_REQUEST';
export type CHANGE_SETTINGS_REQUEST = typeof CHANGE_SETTINGS_REQUEST;

export const CHANGE_SETTINGS_SUCCESS = '@@settings/CHANGE_SETTINGS_SUCCESS';
export type CHANGE_SETTINGS_SUCCESS = typeof CHANGE_SETTINGS_SUCCESS;

export const CHANGE_SETTINGS_FAILURE = '@@settings/CHANGE_SETTINGS_FAILURE';
export type CHANGE_SETTINGS_FAILURE = typeof CHANGE_SETTINGS_FAILURE;

export const SETTINGS_FORM_NAME = 'settings';
