export const GET_PAGES_LIST_REQUEST = '@@login/GET_PAGES_LIST_REQUEST';
export type GET_PAGES_LIST_REQUEST_TYPE = typeof GET_PAGES_LIST_REQUEST;

export const GET_PAGES_LIST_SUCCESS = '@@login/GET_PAGES_LIST_SUCCESS';
export type GET_PAGES_LIST_SUCCESS_TYPE = typeof GET_PAGES_LIST_SUCCESS;

export const GET_PAGES_LIST_FAILURE = '@@login/GET_PAGES_LIST_FAILURE';
export type GET_PAGES_LIST_FAILURE_TYPE = typeof GET_PAGES_LIST_FAILURE;

export const CREATE_PAGE_REQUEST = '@@login/CREATE_PAGE_REQUEST';
export type CREATE_PAGE_REQUEST_TYPE = typeof CREATE_PAGE_REQUEST;

export const CREATE_PAGE_SUCCESS = '@@login/CREATE_PAGE_SUCCESS';
export type CREATE_PAGE_SUCCESS_TYPE = typeof CREATE_PAGE_SUCCESS;

export const CREATE_PAGE_FAILURE = '@@login/CREATE_PAGE_FAILURE';
export type CREATE_PAGE_FAILURE_TYPE = typeof CREATE_PAGE_FAILURE;

export const PAGE_FORM_NAME = 'page';
