export const GET_PAGES_LIST_REQUEST = '@@login/GET_PAGES_LIST_REQUEST';
export type GET_PAGES_LIST_REQUEST_TYPE = typeof GET_PAGES_LIST_REQUEST;

export const GET_PAGES_LIST_SUCCESS = '@@login/GET_PAGES_LIST_SUCCESS';
export type GET_PAGES_LIST_SUCCESS_TYPE = typeof GET_PAGES_LIST_SUCCESS;

export const GET_PAGES_LIST_FAILURE = '@@login/GET_PAGES_LIST_FAILURE';
export type GET_PAGES_LIST_FAILURE_TYPE = typeof GET_PAGES_LIST_FAILURE;

export const PAGE_FORM_NAME = 'page';
